language: node_js

node_js:
  - 'node'

script:
  - npm run lint:js
  - npm run lint:scss
  - npm run build

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  keep_history: true
  on:
    branch: $BUILD_BRANCH
