export const FETCH_FEED_LIST_DATA =
  'HACKER_NEWS/FEED_LIST/FETCH_FEED_LIST_DATA';
export const FETCH_FEED_LIST_DATA_SUCCESS =
  'HACKER_NEWS/FEED_LIST/FETCH_FEED_LIST_DATA_SUCCESS';
export const FETCH_FEED_LIST_DATA_ERROR =
  'HACKER_NEWS/FEED_LIST/FETCH_FEED_LIST_DATA_ERROR';
